### ISSUE TITLE
Decidir representación de piezas en el Tetris

### ISSUE THREAD

**Issue by Franko1307** [LCC-TopicosAvanzadosAI/TetrisAI#4]
No sé qué prefieran en cuanto a la representación

Una es usar representación binaria para representar las piezas del tetris. 
que es, cada pieza representarla en una matriz de 4x4 donde por ejemplo la pieza L 
sería -> ((1,0,0,0),(1,0,0,0),(1,1,0,0),(0,0,0,0)) y eso pasarlo a el número binario 1000 1000 1100 0000
y usar máscaras para obtenerlos y así. Parece ser la manera más eficiente de guardarlos pero no es fácil de leer y es muy difiícil de mantener, ya que si se le quieren añadir características al juego después será más complicado.

La otra es como la puse en el código que es simplemente representarlas así, esta forma requiere más memoria pero es mucho más fácil de leer. Aunque no me gusta cómo se ve en el código.

Qué opinan...

**Comment by fsr313** [comment]
me gusta la forma actual, la memoria no es un problema grande.
Tu codigo es mas limpio que el mio, no continuare programando lo que tenia, hare los to do's de este, parece bastante buena la forma en la que estan ahorita
